# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0004_auto_20190809_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='snippetId',
            field=models.IntegerField(default=1),
        ),
    ]
