# Generated by Django 3.0.5 on 2020-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0007_auto_20200417_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='text',
        ),
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.TextField(default='codeforreview'),
        ),
    ]
