# Generated by Django 3.0.5 on 2020-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0008_auto_20200509_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.TextField(default='clike'),
        ),
    ]
