# Generated by Django 3.0.5 on 2020-06-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0009_snippet_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='linenum',
            new_name='line',
        ),
    ]
