# Generated by Django 3.1.12 on 2021-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0012_waitlistuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='painpoints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
