# Generated by Django 3.1.12 on 2021-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0013_auto_20211010_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='referralUrl',
            field=models.TextField(null=True),
        ),
    ]
