# Generated by Django 3.2.12 on 2023-02-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0014_auto_20211010_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camId', models.IntegerField()),
                ('camUrl', models.URLField()),
                ('camLoc', models.TextField(blank=True)),
                ('metadata', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshotId', models.IntegerField()),
                ('dirLoc', models.TextField()),
                ('capturedTime', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaycode.camera')),
            ],
        ),
    ]
