# Generated by Django 3.1.6 on 2023-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaycode', '0015_camera_snapshotdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camId',
            field=models.IntegerField(max_length=500),
        ),
    ]
